<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom"><title>Giving back to tech - Pylance, Mypy, Python</title><link href="https://jentrialgo.github.io/" rel="alternate"></link><link href="https://jentrialgo.github.io/feeds/pylance-mypy-python.atom.xml" rel="self"></link><id>https://jentrialgo.github.io/</id><updated>2023-06-01T14:00:00+02:00</updated><entry><title>Pylance and mypy cannot find editable local imports</title><link href="https://jentrialgo.github.io/pylance-and-mypy-cannot-find-editable-local-imports.html" rel="alternate"></link><published>2023-06-01T14:00:00+02:00</published><updated>2023-06-01T14:00:00+02:00</updated><author><name>J.E.</name></author><id>tag:jentrialgo.github.io,2023-06-01:/pylance-and-mypy-cannot-find-editable-local-imports.html</id><content type="html">&lt;p&gt;The other day, I wrote &lt;a href="https://jentrialgo.github.io/pylance-cannot-find-editable-local-import.html"&gt;a post&lt;/a&gt;
about how I fixed a problem with Pylance not finding a local import. It worked, but now
mypy was complaining about the same import.&lt;/p&gt;
&lt;p&gt;The solution was installing the package in compat mode with:&lt;/p&gt;
&lt;div class="highlight"&gt;&lt;pre&gt;&lt;span&gt;&lt;/span&gt;&lt;code&gt;pip&lt;span class="w"&gt; &lt;/span&gt;install&lt;span class="w"&gt; &lt;/span&gt;-e&lt;span class="w"&gt; &lt;/span&gt;.&lt;span class="w"&gt; &lt;/span&gt;--config-settings&lt;span class="w"&gt; &lt;/span&gt;&lt;span class="nv"&gt;editable_mode&lt;/span&gt;&lt;span class="o"&gt;=&lt;/span&gt;compat
&lt;/code&gt;&lt;/pre&gt;&lt;/div&gt;</content><category term="Pylance, Mypy, Python"></category><category term="Pylance"></category><category term="Mypy"></category><category term="Python"></category></entry></feed>